### ISSUE TITLE
Gitlab or Github?

### ISSUE THREAD

**Issue by ltsaprounis** [cristiklein/simpy#16]
What's the purpose of this repo? 
I though simpy is hosted on Gitlab -> https://gitlab.com/team-simpy/simpy

**Comment by cristiklein** [comment]
Unfortunately, GitHub requires forking a repository in order to contribute. That is how this repo appeared, back when simpy was hosted on GitHub. I can add a deprecation warning to future readers.

**Comment by ltsaprounis** [comment]
Ah that makes sense! and now that the parent repo is gone there it doesn't show as forked. 
Thanks for the quick response.
